<div class="container">
    <form action="">
        <h2>User Login</h2>
        <label for="inputEmail" class="sr-only">Email Address</label>
        <input type="email" class="form-control" placeholder="Email Address">
        <br>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" class="form-control" placeholder="Password">
        <br>
        <button class="btn bth-lg btn-primary btn-block" type="submit">Login</button>
    </form>
</div>
