<div class="container">
    <form action="">
        <h2 class="form-signin-heading">User Sign-up</h2>
        <label for="inputName" class="sr-only">Name</label>
        <input type="text" class="form-control" placeholder="Full Name">
        <br>
        <label for="inputEmail" class="sr-only">Email Address</label>
        <input type="email" class="form-control" placeholder="Email Address">
        <br>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" class="form-control" placeholder="Password">
        <br>
        <label for="role" class="sr-only">User Role</label>
        <select class="form-control" name="user-role" id="user_role">
            <option value="1">User</option>
            <option value="2">Admin</option>
        </select>
        <br>
        <button class="btn bth-lg btn-primary btn-block" type="submit">Sign-up</button>
    </form>
</div>
